### ISSUE TITLE
Missing conv.h5

### ISSUE THREAD

**Issue by arun-kumark** [emrahbasaran/SPReID#1]
Hi,
I read through the paper and tried executing the code.
Seems something missing.
**it asks for conv.h5, but it's not present.** 
SPReID/data/dump/conv.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

thanks,
Kind Regards
Arun

**Comment by MahdiKalayeh** [comment]
@emrahbasaran due to size limit on GitHub, not all the h5 files are properly uploaded to data/dump. Please update the repo with an external link to Dropbox or GoogleDrive, linking to all the ImageNet pre-trained weights.

**Comment by emrahbasaran** [comment]
I have updated the repo and added the links to the README file.

**Comment by arun-kumark** [comment]
Thanks you !!
