### ISSUE TITLE
in semantic part,how do you decide the segprob?

### ISSUE THREAD

**Issue by yaodonggggggg** [emrahbasaran/SPReID#21]
segprob = F.stack((1.0-y[0],
                    y[1]+y[2]+y[4]+y[13],
                    y[5]+y[6]+y[7]+y[11]+y[10]+y[3]+y[14]+y[15],
                    y[9]+y[16]+y[17]+y[12],
                    y[18]+y[19]+y[8]), axis=1)   
please tell me,why do you know (1.0-y[0]) is oreground,the seconde is head, third is torso-hand, forth is lower-body, last is shoes?
thanks

**Comment by emrahbasaran** [comment]
We built our own semantic segmentation model and trained it using LIP dataset with 20 labels. Please read sections 3.2, 4.2 and 5 of the paper for more information about the model and training procedure.
